### ISSUE TITLE
Behavior when closed all files

### ISSUE THREAD

**Issue by u1035** [AngryCarrot789/sharppad#2]
Hello!)
When I close all files - I still can type text, but there is no more notepad items in list. Also, when last file is closed - it's contents still displayed (and can be edited) in maintextbox. 
Maybe it's better to create new empty file and open it (clearing with it MainTextBox) when all files are closed? I can make a fix for it.
![closeall](https://user-images.githubusercontent.com/30569140/82734263-93107680-9d22-11ea-96b1-9f051eb202bf.png)

**Comment by AngryCarrot789** [comment]
i could probably add a bool to set whether the textbox is enabled or not. that should hopefully fix
