### ISSUE TITLE
Saving/loading selected theme

### ISSUE THREAD

**Issue by u1035** [AngryCarrot789/sharppad#3]
Found that program doesn't remember selected theme (Dark and colouredDark are awesome! :) ).
I found a setting "DarkThemeEnabled", but it's boolean - maybe it should be int, there are more than two themes?
And I found where it is saving, where it is loading, but looks like when theme selected - this property is not set.
I can try to fix it.

**Comment by AngryCarrot789** [comment]
yeah, this sort of broke when i added the colourful themes

**Comment by u1035** [comment]
That's great! :)
